# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
##  distributions: sdist bdist_wheel
#  distributions: bdist_wheel
#  user: c0mpiler
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: hvkrishn/omxware-pypi
#    python: 3.6

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs
  repo: c0mpiler/omxware-pypi-docs
  on:
    branch: master
